service: serverproxy
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  proxy:
    handler: src.lambdas.proxy.lambda_handler
    events:
      - http:
          path: /{any+}
          method: ANY
          caching: #TODO is not free
            enabled: true #TODO is not free
    layers:
      - { Ref: RequestsLambdaLayer }

custom:
  associateWaf: #TODO is not free
    name: waf-proxy #TODO change to ssm
    version: V2

  apiGatewayCaching: #TODO is not free
    enabled: true
    clusterSize: '0.5' # defaults to '0.5'
    ttlInSeconds:  60 # defaults to the maximum allowed: 3600

layers:
  requests:
    path: layers/requests
    name: requests
    compatibleRuntimes:
      - python3.9

plugins:
  - serverless-offline
  - serverless-associate-waf
  - serverless-api-gateway-caching

