service: serverproxy
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: src.lambdas.proxy.lambda_handler
    events:
      - http:
          path: /{any+}
          method: get #ANY
    layers:
      - { Ref: RequestsLambdaLayer }

custom:
  associateWaf:
    name: waf-proxy #TODO change to ssm
    version: V2

layers:
  requests:
    path: layers/requests
    name: requests
    compatibleRuntimes:
      - python3.9

plugins:
  - serverless-offline
  - serverless-associate-waf

