service: serverproxy
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: src.lambdas.proxy.lambda_handler
    events:
      - httpApi:
          path: /{any+}
          method: get
    layers:
      - { Ref: RequestsLambdaLayer }

layers:
  requests:
    path: layers/requests
    name: requests
    compatibleRuntimes:
      - python3.9

plugins:
  - serverless-offline