
CORRECT_REQUEST = {
   "resource":"/{any+}",
   "path":"/categories/MLA5725",
   "httpMethod":"GET",
   "headers":{
      "Accept":"*/*",
      "Accept-Encoding":"gzip, deflate, br",
      "CloudFront-Forwarded-Proto":"https",
      "CloudFront-Is-Desktop-Viewer":"true",
      "CloudFront-Is-Mobile-Viewer":"false",
      "CloudFront-Is-SmartTV-Viewer":"false",
      "CloudFront-Is-Tablet-Viewer":"false",
      "CloudFront-Viewer-ASN":"7418",
      "CloudFront-Viewer-Country":"CL",
      "Host":"09ihufpeu3.execute-api.us-east-1.amazonaws.com",
      "Postman-Token":"7e3c3f08-b33d-4b3e-afa2-03168a75bd9f",
      "User-Agent":"PostmanRuntime/7.30.1",
      "Via":"1.1 fb68992950d3a48e97fdbee744aa9356.cloudfront.net (CloudFront)",
      "X-Amz-Cf-Id":"iqf_G0wY4P4Y8QHcDYcDPOzIL9LgRdqcHdvgxXcpa3Sfu6jke7j_xQ==",
      "X-Amzn-Trace-Id":"Root=1-63f1026b-6c248eb53f5882320cadcfb5",
      "x-api-key":"123123",
      "X-Forwarded-For":"186.107.213.238, 18.68.20.17",
      "X-Forwarded-Port":"443",
      "X-Forwarded-Proto":"https"
   },
   "multiValueHeaders":{
      "Accept":[
         "*/*"
      ],
      "Accept-Encoding":[
         "gzip, deflate, br"
      ],
      "CloudFront-Forwarded-Proto":[
         "https"
      ],
      "CloudFront-Is-Desktop-Viewer":[
         "true"
      ],
      "CloudFront-Is-Mobile-Viewer":[
         "false"
      ],
      "CloudFront-Is-SmartTV-Viewer":[
         "false"
      ],
      "CloudFront-Is-Tablet-Viewer":[
         "false"
      ],
      "CloudFront-Viewer-ASN":[
         "7418"
      ],
      "CloudFront-Viewer-Country":[
         "CL"
      ],
      "Host":[
         "09ihufpeu3.execute-api.us-east-1.amazonaws.com"
      ],
      "Postman-Token":[
         "7e3c3f08-b33d-4b3e-afa2-03168a75bd9f"
      ],
      "User-Agent":[
         "PostmanRuntime/7.30.1"
      ],
      "Via":[
         "1.1 fb68992950d3a48e97fdbee744aa9356.cloudfront.net (CloudFront)"
      ],
      "X-Amz-Cf-Id":[
         "iqf_G0wY4P4Y8QHcDYcDPOzIL9LgRdqcHdvgxXcpa3Sfu6jke7j_xQ=="
      ],
      "X-Amzn-Trace-Id":[
         "Root=1-63f1026b-6c248eb53f5882320cadcfb5"
      ],
      "x-api-key":[
         "123123"
      ],
      "X-Forwarded-For":[
         "186.107.213.238, 18.68.20.17"
      ],
      "X-Forwarded-Port":[
         "443"
      ],
      "X-Forwarded-Proto":[
         "https"
      ]
   },
   "queryStringParameters":"None",
   "multiValueQueryStringParameters":"None",
   "pathParameters":{
      "any":"categories/MLA5725"
   },
   "stageVariables":"None",
   "requestContext":{
      "resourceId":"jhphqq",
      "resourcePath":"/{any+}",
      "httpMethod":"GET",
      "extendedRequestId":"Ai1Q1GAzIAMFiWg=",
      "requestTime":"18/Feb/2023:16:52:59 +0000",
      "path":"/dev/categories/MLA5725",
      "accountId":"865472765923",
      "protocol":"HTTP/1.1",
      "stage":"dev",
      "domainPrefix":"09ihufpeu3",
      "requestTimeEpoch":1676739179429,
      "requestId":"1661d4c0-f1fb-4a27-b45b-b2c8a50086a6",
      "identity":{
         "cognitoIdentityPoolId":"None",
         "cognitoIdentityId":"None",
         "apiKey":"123123",
         "principalOrgId":"None",
         "cognitoAuthenticationType":"None",
         "userArn":"None",
         "userAgent":"PostmanRuntime/7.30.1",
         "accountId":"None",
         "caller":"None",
         "sourceIp":"186.107.213.238",
         "accessKey":"None",
         "cognitoAuthenticationProvider":"None",
         "user":"None"
      },
      "domainName":"09ihufpeu3.execute-api.us-east-1.amazonaws.com",
      "apiId":"09ihufpeu3"
   },
   "body":None
}

CORRUPT_REQUEST = {
   "resource":"/{any+}",
   "path":"/categories/MLA5725",
   "httpMethod":"GET",
   "queryStringParameters":"None",
   "multiValueQueryStringParameters":"None",
   "pathParameters":{
      "any":"categories/MLA5725"
   },
   "stageVariables":"None",
   "requestContext":{
      "resourceId":"jhphqq",
      "resourcePath":"/{any+}",
      "httpMethod":"GET",
      "extendedRequestId":"Ai1Q1GAzIAMFiWg=",
      "requestTime":"18/Feb/2023:16:52:59 +0000",
      "path":"/dev/categories/MLA5725",
      "accountId":"865472765923",
      "protocol":"HTTP/1.1",
      "stage":"dev",
      "domainPrefix":"09ihufpeu3",
      "requestTimeEpoch":1676739179429,
      "requestId":"1661d4c0-f1fb-4a27-b45b-b2c8a50086a6",
      "identity":{
         "cognitoIdentityPoolId":"None",
         "cognitoIdentityId":"None",
         "apiKey":"123123",
         "principalOrgId":"None",
         "cognitoAuthenticationType":"None",
         "userArn":"None",
         "userAgent":"PostmanRuntime/7.30.1",
         "accountId":"None",
         "caller":"None",
         "sourceIp":"186.107.213.238",
         "accessKey":"None",
         "cognitoAuthenticationProvider":"None",
         "user":"None"
      },
      "domainName":"09ihufpeu3.execute-api.us-east-1.amazonaws.com",
      "apiId":"09ihufpeu3"
   },
   "body":None
}